name: Static Web App build & deploy - Maintenance

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    
    strategy:
          matrix:
            node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Azure static web pages cli module install
        shell: bash
        run: npm install -g @azure/static-web-apps-cli

      - name: Static Web Page Deploy
        shell: bash
        run: swa deploy ./public --deployment-token ${{ secrets.AZURE_STATIC_WEB_APP_MAINTENANCE_API_TOKEN }} --env Production
